### ISSUE TITLE
How to disable shortcuts?

### ISSUE THREAD

**Issue by zulhfreelancer** [amandeepmittal/atom-nodejs-snippets#3]
Hi,

From your docs:

> To use, please press tab after shortkeys expressed as following.

Does it possible to turn this off? I'm the person that doesn't like to type and remember shortcuts or alias. But I want to see and use auto-complete suggestions when they are appear.

Please help.

Thank you.

**Comment by amandeepmittal** [comment]
You can avoid pressing tab, that's the solution to your question. Just keep on typing.

**Comment by zulhfreelancer** [comment]
Thanks @amandeepmittal. 🙂
