### ISSUE TITLE
Unable to make edits to nodejs-snippet.cson become active.

### ISSUE THREAD

**Issue by bassamanator** [amandeepmittal/atom-nodejs-snippets#4]
This addon is a lifesaver. I love it.

I'm having an issue however. When I edit nodejs-snippet.cson to change it to my needs, the changes don't take effect.

For example, I added the following under **#node- require core modules ES6**
```
    'const express':
      'prefix': 'exprs'
      'body': "const express = require('express');"
```

and saved the file. But when I type **exprs** and hit tab, nothing happens. **exprs** also doesn't show up in the hints as I'm typing

What am I doing wrong?

**Comment by amandeepmittal** [comment]
Thanks for using it!

Can you try to copy into your own local snippet file? I am not sure how things are nowadays in Atom regarding this matter. I'm not using Atom at the moment.

May be if you could try posting it in the Atom's discussion thread, I think someone will jump to help you.

https://discuss.atom.io/t/snippet-doesnt-work/70971/5

**Comment by bassamanator** [comment]
Ok I'll post the problem there. However, could you please tell me what file I should save my own snippets into? Right now, I've added my own changes to `/home/bassam/.atom/packages/atom-nodejs-snippets/snippets/nodejs-snippet.cson` which isn't working.

**Comment by bassamanator** [comment]
Nvm. I got it working. Thanks!
